title: ANU Auslan Club
description: This site is home to information about the ANU Auslan Club!
theme: just-the-docs
repository: amberave/anuauslanclub.github.io
baseurl: ""
url: https://anuauslanclub.github.io
logo: "/images/general/aac-logo-text.png"
favicon_ico: "/images/general/favicon.ico"

aux_links:
  "Contribute": "https://github.com/amberave/anuauslanclub.github.io"
  Template Repository: https://github.com/just-the-docs/just-the-docs-template