title: ANU Auslan Club
description: This site is home to information about the ANU Auslan Club!
theme: just-the-docs

url: https://anuauslanclub.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
